version: '3'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-opensearch-datasource,esnet-matrix-panel
      - GF_AUTH_GOOGLE_ENABLED=true
      - GF_AUTH_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GF_AUTH_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GF_AUTH_GOOGLE_ALLOWED_DOMAINS=umich.edu
      - GF_AUTH_GOOGLE_SCOPES=openid email profile https://www.googleapis.com/auth/cloud-identity.groups.readonly
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=${GF_SMTP_USER}
      - GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${GF_SMTP_USER}
      - GF_SMTP_FROM_NAME=Grafana

      - GF_SERVER_ROOT_URL=http://pssid-metrics.miserver.it.umich.edu:3000

    volumes:
      - grafana-data:/var/lib/grafana
      - /etc/grafana/saml:/etc/grafana/saml

    networks:
      - opensearch-net
    restart: always

volumes:
  grafana-data:

networks:
  opensearch-net:
    external:
      name: pssid-data-pipeline_opensearch-net
