{
 "title": "ITS network infra",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "198.111.226.182, 198.111.226.190, 198.111.226.184, 198.111.226.159, *"
   },
   { "name": "ssid", "query": "mwireless, eduroam, *" },
   {
    "name": "destination",
    "query": "perfsonar-bin-seb.umnet.umich.edu, perfsonar-core-cool.umnet.umich.edu, *"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "time since last test",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SOURCE=pscheduler_*_*\n| stats max(@timestamp) as last_event by host.name\n| eval now = NOW()\n| fields host.name, last_event, now\n| sort host.name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "probe IP locations",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SOURCE=pscheduler_*\n| eval lat = meta.observer.geo.geo.location.lat\n| eval lon = meta.observer.geo.geo.location.lon\n| eval time = pscheduler.duration\n| fields lat, lon, time",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "throughput mbits $host $ssid to $destination",
   "type": "timeseries",
   "description": "dest: $destination",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "repeat": "host",
   "targets": [
    { "expression": " $A / 1048576", "type": "math" }
   ]
  },
  { "title": "Layer 2 (802.11)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "802.11 duration $host $ssid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "repeat": "host",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SOURCE=`pscheduler_80211_${host}_${ssid}`\n| EVAL timestamp = @timestamp\n| EVAL duration = connectivity.wifi_association_duration_seconds\n| FIELDS timestamp, duration\n| SORT +timestamp",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Layer 3 (DHCP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "dhcp duration $host $ssid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "repeat": "host",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SOURCE=`pscheduler_dhcp_${host}_${ssid}`\n| EVAL timestamp = @timestamp\n| EVAL duration = connectivity.dhcp_lease_duration_seconds\n| FIELDS timestamp, duration\n| SORT +timestamp",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "HTTP $host $ssid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "repeat": "host",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SOURCE=`pscheduler_http_${host}_${ssid}`\n| EVAL timestamp = pscheduler.start_time\n| EVAL http_duration = result.time\n| FIELDS timestamp, http_duration\n| SORT +timestamp",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "mini http matrix",
   "type": "esnet-matrix-panel",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SOURCE=pscheduler_http_198.111.226.*\n| eval http_duration = result.time\n| fields test.spec.url, host.name, http_duration",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "RTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "RTT $host $ssid $destination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "repeat": "host",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SOURCE=`pscheduler_rtt_${host}_${ssid}_${destination}`\n| eval timestamp = pscheduler.start_time\n| eval mean_rtt = result.rtt.mean\n| fields timestamp, mean_rtt\n| sort +timestamp",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Latency $host $ssid $destination",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "repeat": "host",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "luceneQueryType": "Metric",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SOURCE=`pscheduler_latency_${host}_${ssid}_${destination}`\n| eval timestamp = pscheduler.start_time\n| eval mean_latency = result.latency.mean\n| fields timestamp, mean_latency\n| sort +timestamp",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}